Sync with Internal Master Repo

diff --git a/resources/pipeline1.yaml b/resources/pipeline1.yaml
--- a/resources/pipeline1.yaml
+++ b/resources/pipeline1.yaml
@@ -290,6 +290,10 @@ spec:
       default: 'true'
       description: Override DP Gateway image in apiconnect
       type: string
+    - name: DEPLOY_WM_DEV_PORTAL
+      default: 'true'
+      description: Deploy wM Dev Portal
+      type: string
     - name: DEPLOY_FAM
       default: 'true'
       description: Deploy Federated API Management
@@ -348,7 +352,7 @@ spec:
           value: >-
             set -o xtrace
 
-            REPO_SIGNATURE="JGR-20260904-001"
+            REPO_SIGNATURE="JGR-20260907-002"
 
             echo "Setting up workspace for pipeline"
 
@@ -594,7 +598,7 @@ spec:
           value: |-
             set -o xtrace
 
-            CP4I_NAMESPACES=($(params.CP4I_NAMESPACE) $(params.ACE_NAMESPACE) $(params.ES_NAMESPACE) $(params.MQ_NAMESPACE))
+            CP4I_NAMESPACES=($(params.CP4I_NAMESPACE) $(params.ACE_NAMESPACE) $(params.ES_NAMESPACE) $(params.MQ_NAMESPACE) jgrmqapi)
 
             for NS in "${CP4I_NAMESPACES[@]}"
 
@@ -1809,6 +1813,221 @@ spec:
           values: ["true"]
       workspaces:
         - name: cp4i-ws
+    - name: wm-dev-portal-instance-deployment
+      params:
+        - name: SCRIPT
+          value: >-
+            set -o xtrace
+
+            cd workspace/cp4i-ws/cp4i-deployer-helper
+
+            INST_NAME="dev-portal-demo"
+
+            DINST_NAME="apim-demo"
+
+            echo "Getting info from CSV..."
+
+            SUB_NAME=$(oc get deployment ibm-apiconnect -n openshift-operators -o jsonpath='{.metadata.labels.olm\.owner}')
+
+            INST_VER=$(oc get csv $SUB_NAME -n openshift-operators -o json | jq -r '.metadata.annotations."alm-examples" | fromjson | [.[] | select(.kind == "DevPortalCluster")] | .[] | select(.metadata.name == "api-developer-portal") | .spec.version')
+
+            INST_LIC=$(oc get csv $SUB_NAME -n openshift-operators -o json | jq -r '.metadata.annotations."alm-examples" | fromjson | [.[] | select(.kind == "DevPortalCluster")] | .[] | select(.metadata.name == "api-developer-portal") | .spec.license.license')
+
+            INST_PROFILE=$(oc get csv $SUB_NAME -n openshift-operators -o json | jq -r '.metadata.annotations."alm-examples" | fromjson | [.[] | select(.kind == "DevPortalCluster")] | .[] | select(.metadata.name == "api-developer-portal") | .spec.profile')
+
+            echo "Confirming APIC Operator is ready"
+
+            while ! oc wait --for=jsonpath='{.status.phase}'=Succeeded 
+            csv/$SUB_NAME -n $(params.CP4I_NAMESPACE) 2>/dev/null; do sleep 30; done
+            
+            echo "Preparing apic instance manifest"
+
+            ( echo "cat <<EOF" ; cat instances/26-apic-wm-dev-portal-instance.yaml ;) | \
+                INST_NAME=${INST_NAME} \
+                INST_VER=${INST_VER} \
+                INST_LIC=${INST_LIC} \
+                INST_PROFILE=${INST_PROFILE} \
+                DINST_NAME=${DINST_NAME} \
+                sh > apic-wm-dev-portal-instance.yaml
+
+            echo "Deploying wM Dev Portal instance"
+
+            until oc apply -f apic-wm-dev-portal-instance.yaml -n $(params.CP4I_NAMESPACE); do
+                echo "Command oc apply failed. Retrying in 5 seconds..."
+                sleep 5
+            done
+
+            echo "Waiting for wM Dev Portal instance to be ready..."
+
+            while ! oc wait --for=condition=Ready
+            DevPortalCluster/$INST_NAME -n
+            $(params.CP4I_NAMESPACE)  2>/dev/null; do sleep 300; done
+
+            echo "wM Dev Portal instance is ready"
+        - name: VERSION
+          value: latest
+      runAfter:
+        - apic-instance-configuration
+      taskRef:
+        kind: Task
+        name: jgr-task-0.2
+      when:
+        - input: "$(params.CP4I_VERSION)"
+          operator: in
+          values: ["SC2"]
+        - input: "$(tasks.setup-workspace.results.output)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_DATAPOWER_GATEWAY_OPERATOR)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_API_CONNECT_OPERATOR)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_API_CONNECT)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_WM_DEV_PORTAL)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_PLATFORM_UI)"
+          operator: in
+          values: ["true"]
+      workspaces:
+        - name: cp4i-ws
+    - name: wm-dev-portal-instance-configuration
+      params:
+        - name: SCRIPT
+          value: >-
+            set -o xtrace
+
+            cd workspace/cp4i-ws
+
+            echo "Setting flag for apic cli."
+
+            APIC_CLI_FLAG=""
+
+            if [ "$(params.CP4I_VERSION)" = "SC2" ]; then 
+                APIC_CLI_FLAG="--insecure-skip-tls-verify"
+            fi
+
+            echo "Configuring wM Dev Portal instance"
+
+            ./apic $APIC_CLI_FLAG --accept-license --live-help=false
+
+            echo "Setting apic variables"
+
+            INST_NAME="dev-portal-demo"
+
+            NS_NAME="tools"
+
+            APIC_INST_NAME="apim-demo"
+
+            # APIC Local Variables
+
+            APIC_ADMIN_USER='admin'
+
+            APIC_ADMIN_ORG='admin'
+
+            APIC_REALM='admin/default-idp-1'
+
+            APIC_AVAILABILITY_ZONE='availability-zone-default'
+            
+            APIC_SVC_NAME='wm-devportal-service'
+            
+            APIC_INT_NAME='devportal'
+            
+            SVC_TLS_CLIENT_PROFILE_NAME='devportal-admin-client-default'
+            
+            PTL_SVC_TYPE='devportal'
+            
+            APIC_SVC_ID="${APIC_SVC_NAME}-000"
+
+            APIC_MGMT_SERVER=$(oc get route "${APIC_INST_NAME}-mgmt-platform-api" -n $(params.CP4I_NAMESPACE) -o jsonpath="{.spec.host}")
+
+            APIC_ADMIN_PWD=$(oc get secret "${APIC_INST_NAME}-mgmt-admin-pass" -n $(params.CP4I_NAMESPACE) -o jsonpath="{.data.password}"| base64 -d)
+
+            echo "Login to APIC with CMC Admin User..."
+
+            ./apic client-creds:clear $APIC_CLI_FLAG
+
+            ./apic login $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --realm $APIC_REALM -u $APIC_ADMIN_USER -p $APIC_ADMIN_PWD
+
+            echo "Starting wM Dev Portal configuration..."
+
+            echo "Getting Dev Portal Services..."
+
+            ./apic portal-services:list $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --org $APIC_ADMIN_ORG --availability-zone $APIC_AVAILABILITY_ZONE --format json --output .
+
+            echo "Validating if Dev Portal Service Exists..."
+
+            SVC_URL=$(jq -r --arg obj_name $APIC_SVC_NAME '.results[] | select(.name == $obj_name) | .url' PortalServiceList.json)
+
+            if [ -z "$SVC_URL" ]; then
+              echo "Getting Portal Service Integrations..."
+              ./apic integrations:list $APIC_CLI_FLAG --subcollection portal-service --server $APIC_MGMT_SERVER --format json --output .
+              echo "Validating if wM Dev Portal Integration Service Exists..."
+              INT_URL=$(jq -r --arg obj_name $APIC_INT_NAME '.results[] | select(.name == $obj_name) | .url' IntegrationList.json)
+              if [ ! -z "$INT_URL" ]; then
+                echo "Validating if wM Dev Portal TLS Client Profile exists..."
+                ./apic tls-client-profiles:list-all $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --org $APIC_ADMIN_ORG --format json --output .
+                SVC_TLS_CPRO_URL=$(jq -r --arg obj_name $SVC_TLS_CLIENT_PROFILE_NAME '.results[] | select(.name == $obj_name) | .url' TLSClientProfileList.json)
+                if [ ! -z "$SVC_TLS_CPRO_URL" ]; then
+                  echo "Creating wM Dev Portal Service Definition..."
+                  WM_DEV_PORTAL_MGMT_URL="https://$(oc get route ${INST_NAME}-devportal-admin -n $NS_NAME --ignore-not-found -o jsonpath='{.spec.host}')"
+                  WM_DEV_PORTAL_WEB_URL="https://$(oc get route ${INST_NAME}-devportal-web -n $NS_NAME --ignore-not-found -o jsonpath='{.spec.host}')"
+                  ( echo "cat <<EOF" ; cat cp4i-deployer-helper/templates/template-apic-dev-portal-service.json ;) | \
+                    PTL_SVC_TYPE=${PTL_SVC_TYPE} \
+                    APIC_SVC_NAME=${APIC_SVC_NAME} \
+                    APIC_SVC_ID=${APIC_SVC_ID} \
+                    INT_URL=${INT_URL} \
+                    PTL_MGMT_URL=${WM_DEV_PORTAL_MGMT_URL} \
+                    PTL_WEB_URL=${WM_DEV_PORTAL_WEB_URL} \
+                    SVC_TLS_CPRO_URL=${SVC_TLS_CPRO_URL} \
+                    sh > apic-dev-portal-service.json
+                  echo "Creating wM Dev Portal Service..."
+                  ./apic portal-services:create $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --org $APIC_ADMIN_ORG --availability-zone $APIC_AVAILABILITY_ZONE apic-dev-portal-service.json
+                  echo "wM Dev Portal Service $APIC_SVC_NAME has been defined."
+                else
+                  echo "ERROR: wM Dev Portal TLS Client Profile is not available in your APIC stack. Check your environment and try again."
+                fi		
+              else
+                echo "ERROR: wM Dev Portal Integration Service is not available in your APIC stack. Check your environment and try again."
+              fi
+            else
+              echo "wM Dev Portal Service $APIC_SVC_NAME already exists."
+            fi
+        - name: VERSION
+          value: latest
+      runAfter:
+        - wm-dev-portal-instance-deployment
+      taskRef:
+        kind: Task
+        name: jgr-task-0.2
+      when:
+        - input: "$(params.CP4I_VERSION)"
+          operator: in
+          values: ["SC2"]
+        - input: "$(tasks.setup-workspace.results.output)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_DATAPOWER_GATEWAY_OPERATOR)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_API_CONNECT_OPERATOR)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_API_CONNECT)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_WM_DEV_PORTAL)"
+          operator: in
+          values: ["true"]
+        - input: "$(params.DEPLOY_PLATFORM_UI)"
+          operator: in
+          values: ["true"]
+      workspaces:
+        - name: cp4i-ws
     - name: fam-instance-deployment
       params:
         - name: SCRIPT
@@ -1863,7 +2082,7 @@ spec:
         - name: VERSION
           value: latest
       runAfter:
-        - apic-instance-configuration
+        - wm-dev-portal-instance-configuration
       taskRef:
         kind: Task
         name: jgr-task-0.2
@@ -1951,7 +2170,7 @@ spec:
 
             echo "Getting Cloud Settings..."
 
-            ./apic cloud-settings:get --insecure-skip-tls-verify --server $APIC_MGMT_SERVER --format json
+            ./apic cloud-settings:get $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --format json
 
             echo "Validating if Federated API Management is enabled..."
 
@@ -1959,7 +2178,7 @@ spec:
 
             if [ "$FAM_STATUS" != "true" ]; then
               echo "Validating if Federated API Management TLS Client Profile exists..."
-              ./apic tls-client-profiles:list-all --insecure-skip-tls-verify --server $APIC_MGMT_SERVER --org $APIC_ADMIN_ORG --format json --output .
+              ./apic tls-client-profiles:list-all $APIC_CLI_FLAG --server $APIC_MGMT_SERVER --org $APIC_ADMIN_ORG --format json --output .
               SVC_TLS_CPRO_URL=$(jq -r --arg obj_name $SVC_TLS_CLIENT_PROFILE_NAME '.results[] | select(.name == $obj_name) | .url' TLSClientProfileList.json)
               if [ ! -z "$SVC_TLS_CPRO_URL" ]; then
                 echo "Creating Federated API Managememt Definition..."
@@ -1975,13 +2194,13 @@ spec:
                   APIC_MGMT_RUNTIME_NAME=${APIC_MGMT_RUNTIME_NAME} \
                   sh > apic-fam-config.json
                 echo "Configuring Federated API Management..."
-                ./apic cloud-settings:update --insecure-skip-tls-verify --server $APIC_MGMT_SERVER apic-fam-config.json
+                ./apic cloud-settings:update $APIC_CLI_FLAG --server $APIC_MGMT_SERVER apic-fam-config.json
                 echo "Federated API Management has been configured."
               else
                 echo "ERROR: Federated API Management TLS Client Profile is not available in your APIC stack. Check your environment and try again."
               fi
             else
-              echo "Federated API Management is already enabled." "GREEN"
+              echo "Federated API Management is already enabled."
             fi
         - name: VERSION
           value: latest
